<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetExt>.gha</TargetExt>
    <OutputType>Library</OutputType>
    <Title>VectorizeGh</Title>
    <Company>Robert McNeel &amp; Associates</Company>
    <Copyright>Copyright © 2020-2026, Robert McNeel &amp; Associates</Copyright>
    <Product>Vectorize</Product>
    <Description>Vectorize plug-in for Rhinoceros®</Description>
    <Version>9.0.26244.12303</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <OutputPath>..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>..\bin\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VectorizeCommon\VectorizeCommon.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="9.0.26244.12303-beta" IncludeAssets="compile;build" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.0" />
  </ItemGroup>
	<PropertyGroup>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
	</PropertyGroup>
</Project>